:encoding: utf-8
:lang: ja
:author: 著者名
:doctitle: サンプル文書のタイトル: 文書のサブタイトル
:doctype: book
:toc: left

= {doctitle}

[preface]
== はじめに

normal: ここに「はじめに」にあたる文章を書く。

// italicによる強調は「_」で囲む
italic: _ここに「はじめに」にあたる文章を書く。_

// boldによる強調は「*」で囲む
bold: *ここに「はじめに」にあたる文章を書く。*

// bold_italicによる強調は「*_」で囲む
bold_italic: *_ここに「はじめに」にあたる文章を書く。_*

= ここが第1部のタイトル

[partintro]
--
ここは第1部の導入部。ここは第1部の導入部。ここは第1部の導入部。
--

== 最初の章

[.lead]
章のリードが必要ならここに書く。章のリードが必要ならここに書く。章のリードが必要ならここに書く。

=== 最初の章の最初の節

最初の章の最初の節。最初の章の最初の節。最初の章の最初の節。最初の章の最初の節。

==== 最初の章の最初の節の最初の項

最初の章の最初の節の最初の項。最初の章の最初の節の最初の項。その途中に abcefghij abcefghij abcefghij などがあると...。最初の章の最初の節の最初の項。最初の章の最初の節の最初の項。その途中に abcefghij abcefghij abcefghij などがあると...。最初の章の最初の節の最初の項。最初の章の最初の節の最初の項。その途中に abcefghij abcefghij abcefghij などがあると...。

===== その下の項

その下の項。その下の項。その下の項。その下の項。その下の項。その下の項。その下の項。その下の項。その下の項。その下の項。

==== 最初の章の最初の節の2番目の項

最初の章の最初の節の2番目の項。最初の章の最初の節の2番目の項。最初の章の最初の節の2番目の項。

== 次の章

次の章の始まり。

=== 次の章の最初の節

次の章の最初の節。次の章の最初の節。次の章の最初の節。次の章の最初の節。次の章の最初の節。

= これが第2部のタイトル

[partintro]
--
ここは第2部の導入部。ここは第2部の導入部。ここは第2部の導入部。
--

== 第2部の最初の章

[.lead]
章のリードが必要ならここに書く。章のリードが必要ならここに書く。章のリードが必要ならここに書く。章のリードが必要ならここに書く。章のリードが必要ならここに書く。章のリードが必要ならここに書く。

=== 第2部の最初の章の最初の節

第2部の最初の章の最初の節。第2部の最初の章の最初の節。第2部の最初の章の最初の節。

==== 最初の章の最初の節の最初の項

第2部の最初の章の最初の節の最初の項。第2部の最初の章の最初の節の最初の項。第2部の最初の章の最初の節の最初の項。

=== 第2部の次の章

第2部の次の章。第2部の次の章。第2部の次の章。第2部の次の章。第2部の次の章。

:sectnums!:

[appendix]
= 最初の付録

=== 最初の付録のその1

最初の付録のその1のなかみ。

=== 最初の付録のその2

最初の付録のその2のなかみ。

[appendix]
= 次の付録

次の付録のなかみ。
